name: Issue Report
description: File an Issue report
title: "[Issue]: "
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this Issue report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "Please tell us what happened here, also remember to add your JMX Testplan and the Schema you are using here"
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: KloadGen Version
      description: Please let us know which KloadGen Version you are using.
      placeholder: ex. KloadGen 3.5.2
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: jmx
    attributes:
      label: Have you added your JMX Testplan or a replica?
      description: In order to solve your issue we need a JMX testplan or a replica.
      options:
        - label: I have added a JMX testplan
          required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Have you added your Schema or a replica?
      description: In order to solve your issue we need the Schema you are using or a replica.
      options:
        - label: I have added the Schema
          required: true
